from fastmcp import FastMCP

from core.logging import get_logger
from mcp_server.client import MnemosRestClient

logger = get_logger(__name__)


def register(mcp: FastMCP, client: MnemosRestClient) -> None:
  @mcp.tool(
    name="read_wiki_page",
    description="Read a Mnemos wiki page by name. Stale pages are regenerated by the API before the response is returned.",
  )
  def read_wiki_page(name: str) -> dict[str, object]:
    page_name = name.strip()
    if not page_name:
      raise ValueError("name must not be empty")

    page = client.get_wiki_page(page_name)
    found = page is not None
    logger.info(
      "mcp tool read_wiki_page completed",
      extra={
        "event": "mcp_tool_read_wiki_page",
        "page_name": page_name,
        "found": found,
      },
    )
    if page is None:
      return {"found": False, "name": page_name}
    return {"found": True, "page": page.model_dump(mode="json", by_alias=True)}
